### PR TITLE
Bugfix/75 deprecate openssl 1

### PR DESCRIPTION
**Pull request by AssemblyJohn**
## Describe your changes

Removed code calls to Openssl 1.1. Updated CMAKE to have a minimum version of OpenSSL 3.

Closes: https://github.com/EVerest/libevse-security/issues/75 https://github.com/EVerest/libevse-security/issues/38

## Issue ticket number and link

https://github.com/EVerest/libevse-security/issues/75
https://github.com/EVerest/libevse-security/issues/38

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Review by Pietfried — CHANGES_REQUESTED** [review]
Please update the README.md, which says this lib requires Openssl 1.1

**Comment by AssemblyJohn** [comment]
Updated, all entries mentioning OpenSSL.

**Comment by AssemblyJohn** [comment]
> Nice, good for consistency and code clean-up.
> 
> I'd like to see some of the (global) Dockerfiles and build instructions updated. I failed to find libssl3, even as PPA, for Debian 11 and Ubuntu 20.

For Ubuntu 20 the only option is manual install (from sources). Will have to see for Debian.

**Comment by barsnick** [comment]
There are still some references to detection of OpenSSL v3, more code which can be reduced:

```
$ git -C ../libevse-security/ grep -rFn USING_OPENSSL_3  origin/bugfix/75-deprecate-openssl-1
origin/bugfix/75-deprecate-openssl-1:lib/evse_security/crypto/openssl/openssl_tpm.cpp:8:#define USING_OPENSSL_3 (OPENSSL_VERSION_NUMBER >= 0x30000000L)
origin/bugfix/75-deprecate-openssl-1:lib/evse_security/crypto/openssl/openssl_tpm.cpp:10:#if USING_OPENSSL_3 && defined(USING_TPM2)
origin/bugfix/75-deprecate-openssl-1:lib/evse_security/crypto/openssl/openssl_tpm.cpp:17:#define USING_OPENSSL_3_TPM
origin/bugfix/75-deprecate-openssl-1:lib/evse_security/crypto/openssl/openssl_tpm.cpp:45:#ifdef USING_OPENSSL_3_TPM
origin/bugfix/75-deprecate-openssl-1:lib/evse_security/crypto/openssl/openssl_tpm.cpp:223:#else // USING_OPENSSL_3_TPM
origin/bugfix/75-deprecate-openssl-1:lib/evse_security/crypto/openssl/openssl_tpm.cpp:260:#endif // USING_OPENSSL_3_TPM
origin/bugfix/75-deprecate-openssl-1:tests/tests.cpp:20:#define USING_OPENSSL_3 (OPENSSL_VERSION_NUMBER >= 0x30000000L)
origin/bugfix/75-deprecate-openssl-1:tests/tests.cpp:22:#if USING_OPENSSL_3
origin/bugfix/75-deprecate-openssl-1:tests/tests.cpp:52:#endif // USING_OPENSSL_3
origin/bugfix/75-deprecate-openssl-1:tests/tests.cpp:72:#if USING_OPENSSL_3
origin/bugfix/75-deprecate-openssl-1:tests/tests.cpp:125:#endif // USING_OPENSSL_3
```

**Comment by AssemblyJohn** [comment]
Extra dependencies removed.

**Review by Pietfried — APPROVED** [review]

**Pull request merged**
